In [1]:
import mlflow
import mlflow.pytorch
from datetime import datetime

In [2]:
model_uri = "runs:/bec56fbdca2d47f493485ffa1ee700e9/wrapped_lstm_model_with_scaler"
model = mlflow.pytorch.load_model(model_uri)


In [3]:
target_date = "2024-12-01"

In [4]:
db_config = {
    "host": "localhost",
    "port": "5434",
    "dbname": "db",
    "user": "user",
    "password": "password"
}

In [11]:
predictions = model.predict(target_date, db_config, ticker='MSFT',sequence_length=7)

[[ 7.58915750e-01]
 [ 3.50713014e-01]
 [-4.93691135e-01]
 [ 2.68292597e-01]
 [ 7.54412084e-01]
 [-5.11265365e-01]
 [ 4.19303227e+02]]
[[ 3.50713014e-01]
 [-4.93691135e-01]
 [ 2.68292597e-01]
 [ 7.54412084e-01]
 [-5.11265365e-01]
 [ 4.19303227e+02]
 [ 4.18364183e+02]]
[[-4.93691135e-01]
 [ 2.68292597e-01]
 [ 7.54412084e-01]
 [-5.11265365e-01]
 [ 4.19303227e+02]
 [ 4.18364183e+02]
 [ 4.17999685e+02]]
[[ 2.68292597e-01]
 [ 7.54412084e-01]
 [-5.11265365e-01]
 [ 4.19303227e+02]
 [ 4.18364183e+02]
 [ 4.17999685e+02]
 [ 4.17765899e+02]]
[[  0.75441208]
 [ -0.51126537]
 [419.30322709]
 [418.36418267]
 [417.99968508]
 [417.76589904]
 [418.1454479 ]]
[[ -0.51126537]
 [419.30322709]
 [418.36418267]
 [417.99968508]
 [417.76589904]
 [418.1454479 ]
 [417.7275616 ]]
[[419.30322709]
 [418.36418267]
 [417.99968508]
 [417.76589904]
 [418.1454479 ]
 [417.7275616 ]
 [416.58613551]]
[[418.36418267]
 [417.99968508]
 [417.76589904]
 [418.1454479 ]
 [417.7275616 ]
 [416.58613551]
 [417.31839219]]
[[417.999685

In [12]:
import pandas as pd
predictions_df = pd.DataFrame(predictions)
print(predictions_df)

         date  predicted_close
0  2024-11-22       419.303227
1  2024-11-23       418.364183
2  2024-11-24       417.999685
3  2024-11-25       417.765899
4  2024-11-26       418.145448
5  2024-11-27       417.727562
6  2024-11-28       416.586136
7  2024-11-29       417.318392
8  2024-11-30       417.318392
9  2024-12-01       417.318392
